name: Go
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.5
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/.cache/go-build/
            /home/runner/go/pkg/mod/
          key: GO_MOD_CACHE
      - name: Requirements
        run: sudo apt-get install upx-ucl
      - name: Build
        run: ./build.sh
      - name: Store version data
        run: echo "$(git branch --show-current)-$(git rev-parse --short HEAD)" > VERSION
      - name: Upload a Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: |
            ws
            VERSION
  push:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_artifacts
      - name: Draft new release and upload assets
        env: 
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          gh release create "$(cat VERSION)" ./ws